// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfkcIYrLRkEx_EyoEnLhVXmXABIZXib3Y',
    appId: '1:1040579001089:web:14e67ab6b342189f76f900',
    messagingSenderId: '1040579001089',
    projectId: 'stock-flutter-nachit-hatim',
    authDomain: 'stock-flutter-nachit-hatim.firebaseapp.com',
    storageBucket: 'stock-flutter-nachit-hatim.firebasestorage.app',
    measurementId: 'G-M07D2HP6T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZYHMn2iwRQwkcWvTRgvHxVNP8PRpI8yw',
    appId: '1:1040579001089:android:7b26e039119c069b76f900',
    messagingSenderId: '1040579001089',
    projectId: 'stock-flutter-nachit-hatim',
    storageBucket: 'stock-flutter-nachit-hatim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQaYNByZ8_HV1uS-GI6w7OGDAZgMiJluc',
    appId: '1:1040579001089:ios:6d17da74a29d875076f900',
    messagingSenderId: '1040579001089',
    projectId: 'stock-flutter-nachit-hatim',
    storageBucket: 'stock-flutter-nachit-hatim.firebasestorage.app',
    iosBundleId: 'com.example.stockFlutter',
  );
}
